[llm]
model_name = gpt-4o
temperature = 0.1

[app]
personality = -1

[retrieval]
vector_db_output_dir = artifacts/vector_db
vector_backend = faiss
top_k = 10

[data]
product_blurbs = EDA/product_blurbs/combined_blurb_dict.json
images_csv = images.csv

[server]
# Use 0.0.0.0 for Docker port forwarding. For local-only conda use,
# change this to 127.0.0.1.
server_name = 0.0.0.0
server_port = 7860

[evals]
model_name = gpt-4o
temperature = 0.0
